apiVersion: v1
kind: Pod
metadata:
    name: shared-volume-pod
spec:
    containers:
        - name: busybox1
          image: busybox
          command: ['sh', '-c', 'while true; do echo Success! > /output/output.txt; sleep 5; done']
          volumeMounts:
              - name: my-volume1
                mountPath: /output
        - name: busybox2
          image: busybox
          command: ['sh', '-c', 'while true; do cat /input/output.txt; sleep 5; done']
          volumeMounts:
              - name: my-volume1
                mountPath: /input
    volumes:
        - name: my-volume1
          emptyDir: {}