apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-pv
spec:
    storageClassName: localdisk
    persistentVolumeReclaimPolicy: Recycle
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /var/output