apiVersion: v1
kind: Pod
metadata:
    name: always-pod
spec:
    restartPolicy: Always # Always is the default
    containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'sleep 10']