apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-config
    namespace: monitoring
data:
    prometheus.yml: |
        global:
          scrape_interval: 15s
          evaluation_interval: 15s
    
        # Alertmanager configuration
        alerting:
          alertmanagers:
            - static_configs:
                - targets:
                  # - alertmanager:9093
    
        # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
        rule_files:
          # - "first_rules.yml"
          # - "second_rules.yml"
    
        # A scrape configuration containing exactly one endpoint to scrape:
        # Here it's Prometheus itself.
        scrape_configs:
          # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
          - job_name: "prometheus"
    
            # metrics_path defaults to '/metrics'
            # scheme defaults to 'http'.
    
            static_configs:
              - targets: ["localhost:9090"]
    
          - job_name: 'kube-state-metrics'
            static_configs:
              - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
        
          - job_name: 'Node_Exporter'
            scrape_interval: 5s
            static_configs:
                - targets:
                    - 192.168.122.224:9100
                    - 192.168.122.212:9100
                    - 192.168.122.80:9100
                    - 192.168.122.158:9100
        
          - job_name: 'node-exporter'
            kubernetes_sd_configs:
                - role: endpoints
            relabel_configs:
            - source_labels: [__meta_kubernetes_endpoints_name]
              regex: 'node-exporter'
              action: keep
    
          - job_name: kubernetes-nodes-cadvisor
            scrape_interval: 10s
            scrape_timeout: 10s
            scheme: https  # remove if you want to scrape metrics on insecure port
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_node_label_(.+)
              # Only for Kubernetes ^1.7.3.
              # See: https://github.com/prometheus/prometheus/issues/2916
              - target_label: __address__
                replacement: kubernetes.default.svc:443
              - source_labels: [__meta_kubernetes_node_name]
                regex: (.+)
                target_label: __metrics_path__
                replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
            metric_relabel_configs:
              - action: replace
                source_labels: [id]
                regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
                target_label: rkt_container_name
                replacement: '${2}-${1}'
              - action: replace
                source_labels: [id]
                regex: '^/system\.slice/(.+)\.service$'
                target_label: systemd_service_name
                replacement: '${1}'