apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-nfs-storage
    namespace: monitoring
    labels:
        app: grafana
spec:
    storageClassName: managed-nfs
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 500Mi