AWSTemplateFormatVersion: "2010-09-09"
Description: Basic EC2 Instance

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-09e2d756e7d78558d"
      InstanceType: t2.micro
      KeyName: New_Key_Ireland
      SecurityGroups:
        - default
        - Ref: SSHSecurityGroup
        
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SSH security group"
      SecurityGroupIngress:
        - IpProtocol: tcp 
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SSH-SG

  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: 
        Ref: DevEC2Instance
               