AWSTemplateFormatVersion: "2010-09-09"
Description: Mapping demo

Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select the keypair

  EnvironmentName:
    Description: Select the environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Mappings:
  MyRegionMap:
    us-east-1:
      HVM64: ami-026b57f3c383c2eec
    eu-west-1:
      HVM64: ami-09e2d756e7d78558d
    af-south-1:
      HVM64: ami-09513eb71477f1d9b

  MyEnvironmentMap:
    dev:
      InstanceType: t2.micro
    prod:
      InstanceType: t2.small


Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: 
        Fn::FindInMap:
          - MyRegionMap
          - Ref: 'AWS::Region'
          - HVM64
      InstanceType:
        Fn::FindInMap:
          - MyEnvironmentMap
          - Ref: EnvironmentName
          - InstanceType
      KeyName: 
        Ref: MyKeyName
      