---
- hosts: all
  tasks:
    - name: "Install Firewalld"
      package:
        name: firewalld
        state: latest

    - name: "Start firewalld"
      service:
        name: firewalld
        state: started