---
- hosts: all
  tasks:
    - name: "Open apache port 80 and 443"
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      notify: reload_firewall
      loop:
        - 80/tcp
        - 443/tcp  
  handlers:
    - name: reload_firewall
      service:
        name: firewalld
        state: reloaded       