apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingtest
  labels:
    app: pinger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pinger
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pinger
    spec:
      containers:
        - name: ubuntu-ctr
          image: ubuntu:latest
          command:
            - /bin/bash
            - "-c"
            - "sleep 60m"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always    