apiVersion: v1
kind: Pod
metadata:
  name: volpodsc
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: slow
  containers:
    - name: ubuntu-ctr 
      image: ubuntu:latest
      command:
        - /bin/bash
        - "-c"
        - "sleep 60m"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /datasc
          name: data