apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: my-deployment      # must be the same
            
    template:
        metadata:
            labels:
                app: my-deployment  # must be the same
        spec:
            containers:
                - name: nginx
                  image: nginx
                  ports:
                      - containerPort: 80