AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance with Instance profile role to access s3 bucket

Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  MyCICDEC2InstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: MyCICDEC2InstanceProfile
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:Get*'
                  - 's3:List*'
                Resource: '*'

  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref MyCICDEC2InstanceProfileRole

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My SG with port 22 and port 8080 inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0  

  MyStageVmInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09e2d756e7d78558d
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - !Ref MySecurityGroup
      IamInstanceProfile: !Ref MyInstanceProfile
      Tags:
        - Key: Name
          Value: dev
        - Key: Environment
          Value: stage
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update
          sudo yum install ruby
          sudo yum install wget
          sudo yum -y erase java-1.7.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk-devel
          sudo yum -y install tomcat8
          cd /home/ec2-user
          wget https://aws-codedeploy-us-east-2.s3.amazonaws.com/latest/install
          cd +x ./install
          sudo ./install auto

  MyProdVmInstabce:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09e2d756e7d78558d
      InstanceType: t2.micro
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - !Ref MySecurityGroup
      IamInstanceProfile: !Ref MyInstanceProfile
      Tags:
        - Key: Name
          Value: prod
        - Key: Environment
          Value: prod
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update
          sudo yum install ruby
          sudo yum install wget
          sudo yum -y erase java-1.7.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk.x86_64
          sudo yum -y install java-1.8.0-openjdk-devel
          sudo yum -y install tomcat8
          cd /home/ec2-user
          wget https://aws-codedeploy-us-east-2.s3.amazonaws.com/latest/install
          cd +x ./install
          sudo ./install auto

Outputs:
  StageAppURL:
    Description: Staging Application Access URL
    Value: !Sub 'http://${MyStageVmInstance.PublicDnsName}:8080/ccdemo/hello'

  ProdAppURL:
    Description: Production Application Access URL
    Value: !Sub 'http://${MyProdVmInstabce.PublicDnsName}:8080/ccdemo/hello'