apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: grafana
  region: us-east-1

nodeGroups:
  - name: grafana
    instanceType: t3.small
    desiredCapacity: 2

managedNodeGroups:
  - name: grafana-mg
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    desiredCapacity: 2