apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ebs-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
