apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ebs-data
  namespace: monitoring
  labels:
    type: amazonEBS
    app: prometheus-deployment
spec:
  storageClassName: ebs-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0876b24efec5125b9
    fsType: ext4